# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 3600
# Issues with these labels will never be considered stale
exemptLabels:
  - enhancement
  - pinned
  - RFC
  - bug
  - in progress
  - 2.0
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: false
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
